{ pkgs, inputs, ... }: {
  imports = [
    ./alacritty.nix
    #./picom.nix
    ./xsession.nix
    ./xmobar.nix
    ./theme.nix
    ./dunst.nix
    ./qutebrowser.nix
    ./zathura.nix
  ];
  home.packages = with pkgs; [
    onlyoffice-bin
    appimage-run
    #protonvpn-cli_2
    sxiv
    gnome.cheese
    pcmanfm
    #googleearth-pro
    flameshot
    xmobar
    trayer
    #evince
    hsetroot
    tabbed
    #qbittorrent
    python39Packages.ueberzug
    anki-bin
    #ytfzf
    maim
    xdotool
    zoom-us
    #brave
    xclip
    xsel
    dmenu
    authy
    #mpv
    keepassxc
    #mcomix3
  ];
}
